name: muscle_fatigue_tracker
description: 스마트폰 센서 기반 근피로도 측정 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^4.0.2
  rxdart: ^0.27.7
  sqflite: ^2.3.2
  path: ^1.8.3
  # tflite_flutter: ^0.10.4  # TODO: ML 모델 준비 후 활성화
  # http: ^1.1.0               # TODO: 서버 준비 후 활성화
  path_provider: ^2.1.1
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
