name: muscle_fatigue_tracker
description: 스마트폰 센서 기반 근피로도 측정 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^4.0.2
  rxdart: ^0.27.7
  sqflite: ^2.3.2
  path: ^1.8.3
  device_info_plus: ^10.1.0
  tflite_flutter: ^0.10.4
  path_provider: ^2.1.1
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  uuid: ^3.0.7
  google_mobile_ads: ^5.0.0

dependency_overrides:
  tflite_flutter:
    path: third_party/tflite_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
